resolver: lts-12.5

packages:
- .
- location:
    git: https://github.com/runeksvendsen/crypto-depth-db.git
    commit: a362966cb6b1c67f2a2571fcde407292c55dabbb
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/crypto-depth.git
    commit: c2ab2bd1dbac92b9635d190f899cd9c664ca056c
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/crypto-venues.git
    commit: de05c8b2ddd57fd59b19f39938ee01fa9e1b8c20
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/orderbook.git
    commit: 1cfe64aeb59ddebcfb0b8353f82457d16766fa36
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/beam.git
    commit: 62e48d1fd27dc54f73e1184f89c0b52fee7a65d7
    subdirs:
      - beam-core
      - beam-postgres
  extra-dep: true

extra-deps:
- logging-3.0.5@sha256:88096d3124fce9a19af3720f751e1a354d866ed5030d2e5197238d2277cdb2f2
- rate-limit-1.4.1@sha256:27abe882e8b7851202cac124ea2b631e77ab7216f7a655b0782704838fe3c305
- time-units-1.0.0@sha256:27cf54091c4a0ca73d504fc11d5c31ab4041d17404fe3499945e2055697746c1
